# Generated by Django 4.2.11 on 2025-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded-files/')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
